<#-- $This file is distributed under the terms of the license in LICENSE$ -->

${stylesheets.add('<link rel="stylesheet" href="${urls.base}/css/askvivo/askVivo.css" />')}

<h2>Ask VIVO</h2>

<#if !configured>
    <div class="askvivo-notice" role="alert">
        <h3>Ask VIVO is not configured</h3>
        <p>
            This page needs an OpenAI-compatible language-model endpoint. An administrator must add
            the following properties to <code>runtime.properties</code> and restart VIVO:
        </p>
        <ul>
            <li><code>llm.baseUrl</code> &ndash; base URL of the API,
                e.g. <code>https://api.openai.com/v1</code></li>
            <li><code>llm.apiKey</code> &ndash; API key (may be left empty for keyless local
                gateways)</li>
            <li><code>llm.model</code> &ndash; name of the model to use</li>
        </ul>
    </div>
<#else>
    <div id="askvivo">
        <p class="askvivo-intro">
            Ask a question about the people, publications, grants and organizations in this system,
            in plain language. For example: <em>&ldquo;Who has published on machine
            learning?&rdquo;</em> or <em>&ldquo;Which grants is Jane Smith a principal investigator
            on?&rdquo;</em>
        </p>
        <div id="askvivo-messages" aria-live="polite"></div>
        <form id="askvivo-form" action="#">
            <textarea id="askvivo-question" rows="2"
                placeholder="Type your question and press Enter&hellip;"></textarea>
            <button type="submit" id="askvivo-send">Ask</button>
        </form>
        <p class="askvivo-hint">
            Answers are generated by a language model from a database query and may be incomplete.
        </p>
    </div>

    <script type="text/javascript">
        var askVivoBaseUrl = '${urls.base}';
    </script>
    ${scripts.add('<script type="text/javascript" src="${urls.base}/js/askvivo/askVivo.js"></script>')}
</#if>
